# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: assignment
    # the password
    password: 1234
    # the JDBC URL; the database is called assignment
    url: jdbc:mysql://localhost:3306/assignment

#    properties:
#        hibernate.dialect: org.hibernate.dialect.MySQLDialect
#        hibernate.hbm2ddl.auto: create

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG
