package vandebron.jdbi;

import javax.persistence.*;

/**
 * Created by leobel on 5/16/17.
 */

@Entity
@Table(name = "addresses")
@NamedQueries({
        @NamedQuery(name = "vandebron.jdbi.Address.findAll",
                query = "select a from Address a")
})
public class Address {

    /**
     * Address's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /**
     * Address name.
     */
    @Column(name = "name")
    private String name;

    /**
     * Address ManyToOne relationship.
     */

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinTable(name="customers_address",
            joinColumns = @JoinColumn(name="address_id"),
            inverseJoinColumns = @JoinColumn(name="customer_id")
    )
    private Customer customer;


    /**
     * A no-argument constructor.
     */
    public Address(){

    }

    /**
     * A constructor to create address. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Address(String name, Customer customer){
        this.name = name;
        this.customer = customer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
}
